### ISSUE TITLE
Filters no longer allow RegEx

### ISSUE THREAD

**Issue by IzzySoft** [mediathekview/MediathekView#567] opened 2020-11-22 14:09 UTC
In previous versions, one could set up RegEx for the 3 possible filters. I used that to filter for documentations and movies separately:

```
#:(.*doku.*|dokfilm|dox.*)
#:(Filme?( im (ersten|ndr|rbb))?|Spielfilm|Fernsehfilm.*|Film (&amp;|und) Serie|filmmittwoch im ersten|kino . (kurz)?filme|film.?)
```

While such filters still work in the search box, at least with 13.6 they do not work in the filter settings themselves. As especially the RegEx for movies is a bit longer, always adding it manually is not really a "workable solution".

Added to that, which I consider a bug: As soon as I add some term to one filter, this is copied and applied to ALL filters. I don't think that was intended.

Not being able to combine multiple topics into one and other topics into another filter is a huge step back as well – though the speed filtering now works with is amazing (before, I've used version 10.2 which came as package with my distribution).

Besides: Has someone ever tried explaining to the editors what the difference is between "topic" ("Thema") and "title" ("Titel")? Hard to have reliable filters on "topic" if they just copy the title over (for series even including the part at times)…

**Comment by derreisende77** [comment] 2020-11-22 18:57
Why shouldn´t the regexp not work? If I put your longer regexp into a filter I get on my setup additional 3k entries for download:
![Bildschirmfoto 2020-11-22 um 19 49 57](https://user-images.githubusercontent.com/8466092/99914271-70c0db00-2cfc-11eb-95fb-7335a8faebdb.jpg)

Regarding your bug with the filter copies: Can you provide screenshots as I cannot reproduce this problem.

Also it would be great on what OS you are running MV.

For your sidenote: No, we crawl the entries direct from each provider and thats the info we ge, there are no human editors involved. Maybe the [forum](forum.mediathekview.de) can be of help on how to set up better filters as there are quite some capable users there which use regex a lot.

**Comment by IzzySoft** [comment] 2020-11-22 20:03
Thanks for the fast response!

> If I put your longer regexp into a filter I get on my setup additional 3k entries for download:

You're in the Abo screen, that's not what I'm talking about:

[<img src="https://user-images.githubusercontent.com/6781438/99915415-d6649580-2d03-11eb-86c6-fed60a8e4734.png" width="250">](https://user-images.githubusercontent.com/6781438/99915415-d6649580-2d03-11eb-86c6-fed60a8e4734.png) [<img src="https://user-images.githubusercontent.com/6781438/99915453-fe53f900-2d03-11eb-9d5b-21d232e60ee4.png" width="250">](https://user-images.githubusercontent.com/6781438/99915453-fe53f900-2d03-11eb-9d5b-21d232e60ee4.png)

(the very same screen: first pic with the RegEx in, second just the RegEx removed)

But thanks for picking that: I have no Abos, so I totally ignored that. Now I'm using an inactive Abo as clipboard until RegEx start working properly in the other filter :smile:

And the bug is with the very same filter. I can of course provide screenshots for that as well – or you substitute the first one above and think another name into the drop-down on top (which currently says "Letzte 3 Wochen"). Whatever I put into "Thema" gets copied to **all** sets.

> No, we crawl the entries direct from each provider and thats the info we ge

Aw, apologies for not being clear: I of course didn't mean **you** would do such crazy stuff! I meant those folks at the broadcast stations (or providers) who provide the data. I've read the docs before posting here, so let me make a reference: being able to tell what time a certain redactor was on vacation? :laughing:

**Comment by derreisende77** [comment] 2020-11-22 20:47
Okay, I think you are "misusing" the program. The "Thema" Dropdown provides a dynamically generated list of all themas available in the filmlist. It also provides auto-completion functionality, which means you can enter party of themas and the list will shrink so you can find themas easier. Please see [this picture (Filme Übersicht - Filter Panel)](https://mediathekview.de/screenshots/). **It is not meant to insert regex there**. This was never planned and is not a bug. The only place where regex will work is search bar and abos(and blacklist). 

And according to the release notes, changes to the sender and thema area are currently **not** considered when saving filters, therefore changing a filter should not change them. It´s not a bug, it´s a feature ;)

**Comment by IzzySoft** [comment] 2020-11-22 21:40
Well, as I pointed out: I just migrated from version 10.2 – and there it **was** possible. Thinking about it, it was a bit different though: one could "save searches" to the ① ② ③ buttons (which are no longer there with 13.6) and then simply click them to apply the search (filter).

So how to get that functionality back? How does one easily switch between "show all movies" versus "show all documentaries" versus "show all music" (or whichever criteria one feels important and has created more-or-less complex searches for)? If that's no longer possible, that's a setback (at least for me, as I've used that daily). As I still have the old version installed, I can provide screenshots if you wish.

Would it maybe be possible to show the abos as tab (next to "Filme" and "Downloads") and having an option to just "show" them instead of recording – if that's easier to achieve then restoring the "saved searches" functionality? Or re-introduce "saved searches"? "Bookmark" searches? Have a search history (ideally editible, so one can remove unwanted ones)? A set of 3 "saved searches" (as it was before) might be limited, but would still be very welcome. (I'm just brain-storming possibilities here in the hope to make a hit, please do not understand it as a "demand": I know what it means to maintain free software, I'm a maintainer at multiple projects myself, so I'm grateful for what you do!)

As for the "Copy-Bug": that's not limited to RegEx. Regardless what I put in to "Thema", it gets copied to **all** filter sets – whether I enter it manually, or select it from the drop-down.

> changes to the sender and thema area are currently not considered when saving filters, therefore changing a filter should not change them. It´s not a bug, it´s a feature ;)

Now you've got me confused. If they are not considered as part of the specific filter, why are they part of the filter view in the first place? That's not intuitive. But your remark just made me look again: That "box" is what was the "side-bar" in v10.2, indeed! And, sorry if I say so, that was exactly where I had used the RegEx (and saved them to the ① ② ③ buttons – which, if thinking further, have been replaced by the drop-down)… :flushed:

**Comment by derreisende77** [comment] 2020-11-23 10:22
Okay, you are upgrading from a 5 year old version. During these 5 years many things have changed and none of the behaviour you described so far is a bug in the current release. I would suggest that you ask for help in [the forum](https://forum.mediathekview.de) as between your version and the current have been 15 updates.
Issues are not for asking for help therefore I am going to close this issue and ask you to contact the forum.

**Closed by derreisende77** 2020-11-23 10:22 UTC

**Comment by IzzySoft** [comment] 2020-11-23 12:50
Understood, thanks. And feature-requests (like re-establishing those "saved searches") would go to the forum, or here? I assume here (as I see several feature requests in the issue list)?

**Comment by derreisende77** [comment] 2020-11-26 07:04
Feature requests can be made here, one issue per request and plz with a good explanation what and why you want to have it so I dont have to spend hours trying to figure out what might be meant. Also, most of the time I need to know, what OS, how much RAM,etc for bugs/errors etc.
