### ISSUE TITLE
13.3 Custom download path ignored on macos

### ISSUE THREAD

**Issue by fiwswe** [mediathekview/MediathekView#435] opened 2019-08-09 20:46 UTC
MediathekView 13.3, macOS 10.11.6

I have set a custom download path in the preferences "Aufzeichnen und Abspielen" -> "Set bearbeiten" -> "Mac Speichern" -> "Speicherziel". The path points to a volume which is not the root volume, e.g. "/Volumes/VolName/Neue Filme". in MV 13.2.1 this worked fine. In version 13.3 MV downloads to "\~/Downloads/Filme1/" ignoring the setting. (There was already an object named "Filme" in "\~/Downloads" so I suspect the name was changed to "Filme1".)

Expected behavior: Download to the path specified in the preferences.

**Comment by JayBrown** [comment] 2019-08-10 09:34
It looks like something went wrong with the download presets. I only have one preset, always downloading to ~/Downloads/Media/Mediathek, and v13.3.0 honored this setting just fine.

But I did have to edit my setting once, because I had to remove the path to flvstreamer—it's not bundled anymore—, and MediathekView had changed the VLC and ffmpeg paths from ~/Applications to /Applications. This seems to be another bug: MediathekView apparently doesn't recognize when it's launched from a different path than /Applications and always assumes it will be installed in the latter location… be that as it may, maybe editing your presets will make MediathekView behave again.

**Comment by derreisende77** [comment] 2019-08-10 11:29
> It looks like something went wrong with the download presets. I only have one preset, always downloading to ~/Downloads/Media/Mediathek, and v13.3.0 honored this setting just fine.
> 
> But I did have to edit my setting once, because I had to remove the path to flvstreamer—it's not bundled anymore—, and MediathekView had changed the VLC and ffmpeg paths from ~/Applications to /Applications. This seems to be another bug: MediathekView apparently doesn't recognize when it's launched from a different path than /Applications and always assumes it will be installed in the latter location… be that as it may, maybe editing your presets will make MediathekView behave again.

Since the beginning of MV it should never be installed outside of /Applications. It is a java app not a native macOS app and relies on some static paths.

**Comment by fiwswe** [comment] 2019-08-10 19:43
> > It looks like something went wrong with the download presets. I only have one preset, always downloading to ~/Downloads/Media/Mediathek, and v13.3.0 honored this setting just fine.
> > But I did have to edit my setting once, because I had to remove the path to flvstreamer—it's not bundled anymore—, and MediathekView had changed the VLC and ffmpeg paths from ~/Applications to /Applications. This seems to be another bug: MediathekView apparently doesn't recognize when it's launched from a different path than /Applications and always assumes it will be installed in the latter location… be that as it may, maybe editing your presets will make MediathekView behave again.
> 
> Since the beginning of MV it should never be installed outside of /Applications. It is a java app not a native macOS app and relies on some static paths.

First of all a well behaved macOS app should not care from where it is launched. The end user doesn't care about the development language or runtime so Java is no excuse IMHO. 

That being said, originally the app package was in a subfolder of "/Applications". I tested again with the app directly in "/Applications" and nothing changed.

I also tested without an object "\~/Downloads/Filme" present and the download destination was still "\~/Downloads/Filme1/" while the preferences setting was "/Volumes/VolName/Neue Filme".

It looks like the preference for the download path is completely ignored in version 13.3.0.

Workaround / possibly resolution?
Only after manually clearing the download path in the download dialog and then clicking the "History löschen" button did the correct download path as defined in the preferences work again. So the issue might be related to the download path history in some fashion. I can't see how the "\~/Downloads/Filme1/" managed to get in there though as I don't recall ever having used that path.

**Comment by JayBrown** [comment] 2019-08-11 10:10
> Since the beginning of MV it should never be installed outside of /Applications. It is a java app not a native macOS app and relies on some static paths.

I've always had it in ~/Applications, which by the way is one of the default app locations on macOS, just like /Developer/Applications, ~/Developer/Applications, /Network/Applications, /Network/Developer/Applications etc., and I never had any problems except for the need to edit my download/playback sets. So I guess it's safe to run the app from other paths than the global /Applications directory.

PS @fiwswe : are you using the tilde (~) for the path in your preferences? Maybe you could try to expand the tilde to the full path, i.e. `/Users/<yourUsername>`

**Comment by derreisende77** [comment] 2019-08-11 15:37
@fiwswe First of all, MV is a cross-platform java application. The macOS version is packed into a wrapper launcher to simplify usage on macOS. It does not use a single macOS API hence it is not a well-behaved macOS app. It tries however to adhere to some conventions.

**Comment by fiwswe** [comment] 2019-08-11 16:11
> PS @fiwswe : are you using the tilde (~) for the path in your preferences? Maybe you could try to expand the tilde to the full path, i.e. `/Users/<yourUsername>`

No, the actual path does not include a tilde (\~). I just used this to illustrate that the path was inside the current user home directory. Since I was not referring to an actual setting, just to the result of whatever happened in MV, I thought this to be more clear to the reader.

**Comment by fiwswe** [comment] 2019-08-11 16:17
> @fiwswe First of all, MV is a cross-platform java application. The macOS version is packed into a wrapper launcher to simplify usage on macOS. It does not use a single macOS API hence it is not a well-behaved macOS app. It tries however to adhere to some conventions.

Understood. While this is obvious to someone familiar with macOS development, the average user would not really care though. All in all MV does a pretty good job of behaving like a good macOS app. Even running from a non-standard location (a subfolder of /Applications) works the same as from the standard location despite your warnings.

**Comment by derreisende77** [comment] 2019-08-11 16:51
The problem is it "may" work. I have seen this several times that it works on a specific macOS version while it doesn´t work with others. This is something really hard to trace therefore we keep up the warning not to do it. If it works that´s great but we had bad luck in history.
I am thinking about dropping java for macOS and doing a new version which will be a "true" macOS version. Mojava and Catalina are a nightmare due to the new security features.

**Comment by styroll** [comment] 2019-08-12 17:53
> @fiwswe sagte: Even running from a non-standard location (a subfolder of /Applications) works the same as from the standard location despite your warnings.

Well, then try to download a film from SRF, ORF or WDR…

**Comment by fiwswe** [comment] 2019-08-12 18:18
> Well, then try to download a film from SRF, ORF or WDR…

No problems so far …

**Comment by styroll** [comment] 2019-08-12 18:21
>No problems so far …

Not with default config (without changing the path to ffmpeg in the prefs)

**Comment by fiwswe** [comment] 2019-08-12 18:36
> > No problems so far …
> 
> Not with default config (without changing the path to ffmpeg in the prefs)?

Hmm, I just checked: The paths to ffmpeg, flvstreamer and VLC in the prefs are indeed pointing inside my subfolder of /Applications. If I changed that, it must have been a long time ago for an older version of MV.

Not sure what a simple HTTP(s) download would need a helper app for though. But I admit I haven't checked the code. Does MV transcode the downloaded data? MVWeb just asks the browser to download from the appropriate URL, depending on the selected quality/resolution. I had thought MV would do the same.

**Comment by styroll** [comment] 2019-08-12 18:44
> Not sure what a simple HTTP(s) download would need a helper app for though.

Direct downloads don't need a helper tool, but HL streams do (https://…*.m3u3). That's why MVW fails here…

>Does MV transcode the downloaded data?

Kind of transcoding in the latter case (handled by ffmpeg, if in the proper path), but no conversion is applied.

**Comment by JayBrown** [comment] 2019-09-07 11:25
> > @fiwswe sagte: Even running from a non-standard location (a subfolder of /Applications) works the same as from the standard location despite your warnings.
> 
> Well, then try to download a film from SRF, ORF or WDR…

Just tested a download from WDR & SRF, all fine. Downloading from ORF failed ("fehlerhaft"). But I can live with that.

**Closed** 2019-09-11 14:50 UTC
