### ISSUE TITLE
"Change Download" dialog does not remember size

### ISSUE THREAD

**Issue by ushuc** [mediathekview/MediathekView#693] opened 2023-04-25 19:50 UTC
Downloads can be changed on an individual basis, which is a good feature (see screenshot 1). But the dialog window (Screenshot 2) does not remember the size. So every time I change a download I have to manually resize this window again and again.
Please make this window remember the size that the user has set.

**Screenshot 1**
![grafik](https://user-images.githubusercontent.com/109863013/234386001-b8bc5d29-539a-4265-a057-f8eec624372c.png)

**Screenshot 2**
![grafik](https://user-images.githubusercontent.com/109863013/234386551-a7463e5c-eb75-470c-b6c7-a611b165433b.png)

**Comment by derreisende77** [comment] 2023-05-02 10:34
it is not a bug as it was never meant to save it dialog size.
Maybe I am going to add this functionality before release.

**Comment by styroll** [comment] 2023-05-04 07:57
>@derreisende77 said: Maybe I am going to add this functionality before release.

An advantage of this would be at least on wider screens: You don't have to scroll to the left every time you change the URL to get an other quality. On SRF for example changing "f6" to "f5" results in HD instead of UHD (cf. the following screenshot):

<img width="1440" alt="Screenshot_ 2023-05-04 at 09 48 01" src="https://user-images.githubusercontent.com/24810728/236143501-f096a4ea-9332-48db-8262-c659adbb506c.png">

**Comment by derreisende77** [comment] 2023-05-08 19:56
I forgot that this feature was already implemented for MV 14 😆 I documented it in the CHANGELOG and it will be available in the next release. Therefore I am going to close this issue.

**Closed by derreisende77** 2023-05-08 19:56 UTC
Labels: enhancement
